#! /bin/sh
### BEGIN INIT INFO
# Provides:          vending_tweet
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts python tweeter
### END INIT INFO

case "$1" in
  start)
        /home/pi/tweet.sh &
        ;;
  restart|reload|force-reload)
        ;;
  stop)
        kill -9 $(pidof python)
        ;;
  *)
        echo "Usage: $0 start|stop"
        ;;
esac

